 const   Data = [
    {
        id: 1,
        title: 'Beautiful and dramatic Antelope Canyon',
        subtitle: 'Lorem ipsum dolor sit amet et nuncat mergitur',
        illustration: 'https://i.imgur.com/UYiroysl.jpg',
        category: 'science',
        time: '2h ago',
        date: '10 January'
      },
      {
        id: 2,
        title: 'Earlier this morning, NYC',
        subtitle: 'Lorem ipsum dolor sit amet',
        illustration: 'https://i.imgur.com/UPrs1EWl.jpg',
        category: 'Health',
        time: '2h ago',
        date: '12 January'
      },
      {
        id: 3,
        title: 'White Pocket Sunset',
        subtitle: 'Lorem ipsum dolor sit amet et nuncat ',
        illustration: 'https://i.imgur.com/MABUbpDl.jpg',
        category: 'LifeStyle',
        time: '2h ago',
        date: '15 January'
      },
      {
        id: 4,
        title: 'Acrocorinth, Greece',
        subtitle: 'Lorem ipsum dolor sit amet et nuncat mergitur',
        illustration: 'https://i.imgur.com/KZsmUi2l.jpg',
        category: 'Technology',
        time: '2h ago',
        date: '18 january'
      },
      {
        id: 5,
        title: 'The lone tree, majestic landscape of New Zealand',
        subtitle: 'Lorem ipsum dolor sit amet',
        illustration: 'https://i.imgur.com/MABUbpDl.jpg',
        category: 'Entertainment',
        time: '2h ago',
        date: '20 january'
      },
]
export default Data;

export const jobData = [
  {
    id: 1,
    title: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse nec sem et dolor',
    
    date: '20/1/2025',
    lastDate: '22/3/2025',
    payDate: '28/3/2025',
    correctionDate: '12 Febuary 2025 to 15 february 2025',
    Examdate: '5/5/2025',
    admitcard: '16/3/2025',
    postName:'Indian Administrative Service (IAS)',
    TotalPost:'119',
    Eligibility:'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse nec sem et dolor',

  },
  {
    id: 2,
    title: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse nec sem et dolor',
    date: '22/1/2025',
    lastDate: '22/3/2025',
    payDate: '28/3/2025',
    correctionDate: '12 Febuary 2025 to 15 february 2025',
    Examdate: '5/5/2025',
    admitcard: '16/3/2025',
    postName:'Indian Forest Service (IFS)',
    TotalPost:'113',
    Eligibility:'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse nec sem et dolor',
  },
  {
    id: 3,
    title: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse nec sem et dolor',
    date: '26/1/2025',
    lastDate: '22/3/2025',
    payDate: '28/3/2025',
    correctionDate: '12 Febuary 2025 to 15 february 2025',
    Examdate: '5/5/2025',
    admitcard: '16/3/2025',
    postName:'Indian Forest Service (IFS)',
    TotalPost:'113',
    Eligibility:'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse nec sem et dolor',
  },
  {
    id: 4,
    title: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse nec sem et dolor',
    
    date: '31/1/2025',
    lastDate: '22/3/2025',
    payDate: '28/3/2025',
    correctionDate: '12 Febuary 2025 to 15 february 2025',
    Examdate: '5/5/2025',
    admitcard: '16/3/2025',
    postName:'Indian Forest Service (IFS)',
    TotalPost:'113',
    Eligibility:'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse nec sem et dolor',
  },
  {
    id: 5,
    title: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse nec sem et dolor',
    date: '3/2/2025',
    lastDate: '22/3/2025',
    payDate: '28/3/2025',
    correctionDate: '12 Febuary 2025 to 15 february 2025',
    Examdate: '5/5/2025',
    admitcard: '16/3/2025',
    postName:'Indian Forest Service (IFS)',
    TotalPost:'113',
    Eligibility:'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse nec sem et dolor',
  },
  {
    id:6,
    title: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse nec sem et dolor',
    
    date: '23/2/2025',
    lastDate: '22/3/2025',
    payDate: '28/3/2025',
    correctionDate: '12 Febuary 2025 to 15 february 2025',
    Examdate: '5/5/2025',
    admitcard: '16/3/2025',
    postName:'Indian Forest Service (IFS)',
    TotalPost:'113',
    Eligibility:'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse nec sem et dolor',
  },
  {
    id: 7,
    title: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse nec sem et dolor',
    
    date: '2/3/2025',
    lastDate: '22/3/2025',
    payDate: '28/3/2025',
    correctionDate: '12 Febuary 2025 to 15 february 2025',
    Examdate: '5/5/2025',
    admitcard: '16/3/2025',
    postName:'Indian Forest Service (IFS)',
    TotalPost:'113',
    Eligibility:'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse nec sem et dolor',
  },
    {
      id: 8,
      title: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse nec sem et dolor',
      
      date: '2/3/2025',
      lastDate: '22/3/2025',
      payDate: '28/3/2025',
      correctionDate: '12 Febuary 2025 to 15 february 2025',
      Examdate: '5/5/2025',
      admitcard: '16/3/2025',
      postName:'Indian Forest Service (IFS)',
      TotalPost:'113',
      Eligibility:'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse nec sem et dolor',
    },
    {
      id: 9,
      title: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse nec sem et dolor',
      
      date: '2/3/2025',
      lastDate: '22/3/2025',
      payDate: '28/3/2025',
      correctionDate: '12 Febuary 2025 to 15 february 2025',
      Examdate: '5/5/2025',
      admitcard: '16/3/2025',
      postName:'Indian Forest Service (IFS)',
      TotalPost:'113',
      Eligibility:'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse nec sem et dolor',
    },
    {
      id: 10,
      title: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse nec sem et dolor',
      date: '10/3/2025',
      lastDate: '22/3/2025',
      payDate: '28/3/2025',
      correctionDate: '12 Febuary 2025 to 15 february 2025',
      Examdate: '5/5/2025',
      admitcard: '16/3/2025',
      postName:'Indian Forest Service (IFS)',
      TotalPost:'113',
      Eligibility:'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse nec sem et dolor',
    },


]

